package com.example.webapp.dto;

import lombok.Data;
import lombok.Getter;
import lombok.Setter;
import java.util.Set;

@Data
public class StudentDTO {

    private Long id; // Added for edit functionality
    private String name;

    private String roll;

    private Set<Long> selectedCourseIds; // Field to hold selected course IDs

    // Getters and Setters will be generated by Lombok's @Data annotation
    // Remove existing explicit getters/setters if @Data is uncommented to avoid redundancy
    
}
